server:
  port: 8085

spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

telegram:
  bot:
    token: ${BOT_TOKEN}

services:
  quiz-service:
    base-url: ${QUIZ_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      service: ${spring.application.name}

logging:
  level:
    root: INFO
    uz.quizplatform: DEBUG
