{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-service
  labels:
    app: {{ $name }}-service
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}-service
  template:
    metadata:
      labels:
        app: {{ $name }}-service
    spec:
      containers:
        - name: {{ $name }}-service
          image: "{{ $.Values.global.imageRegistry }}/{{ $name }}-service:{{ $.Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $svc.port }}
          envFrom:
            - secretRef:
                name: {{ $.Release.Name }}-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
{{- end }}
