apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: quiz-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/quizplatform"
  SPRING_DATASOURCE_USERNAME: "quizplatform"
  SPRING_DATASOURCE_PASSWORD: "quizplatform"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
  BOT_TOKEN: "8711346660:AAE-f2Cy7FOfnRzpNDck5YZJeQUPqp8CK-8"
  BOT_USERNAME: "randomche_bot"
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
